### PR TITLE
Consistent path variables across control scripts

### PR DESCRIPTION
**Pull request by Izhmash**
- hil_slurm_monitor.sh, hil_slurmctld_prolog.sh, and hil_slurmctld_epilog.sh are now combined into one file: hil_slurmctld_master.sh.
- An argument must be passed to select the function: prolog, epilog, monitor, network (future).
- ulsr_provision_controller_centos.sh has been edited to support this singular script.
    - ulsr_provision_controller_centos.sh now enters the `LOGFILE` and `HOME` directories into hil_slurmctld_master.sh

@tpd001 Let me know if this matches what you were hoping for the simplified control scheme.  I can update the documentation accordingly after resolving any issues you may have.

### CODE REVIEW

**Comment by Izhmash** [comment]
I figured that this master script would be called in the same manner that the prolog and epilog were going to be called.  How were the epilog and prolog scripts going to be called before?

**Comment by tpd001** [comment]
The prolog and epilog are invoked by the Slurm control daemon, as described in the README.  They are specified in the slurm.conf file.  Not sure it is possible to configure the control daemon to pass args to them.  Perhaps it is possible to modify the shell script path variables, then copy the shell script to uniquely-named scripts (as we have now), then detect which was invoked through a bash function?  $0 or a variant?

**Comment by Izhmash** [comment]
Ok, I understand now.  I didn't know that prolog and epilog were slurm-specific functions, so I assumed that the parameters could be passed.  In this case, the cleanest solution may be to go back to having individual script files and copy the path variables to each script.

While there will be more files, the logical flow would be easier to follow, I believe.  Which might you prefer, keeping the singular script or returning to multiple files?

**Comment by tpd001** [comment]
Ian, do you want to keep this request open?

**Comment by Izhmash** [comment]
I'm going to edit the name to keep it up to date with our new plans. It
might be helpful down the road to see when a decision was made not to have
one singular control script. If you'd like we can close it for now and I
can open it again when the changes are ready.

On Nov 9, 2017 10:09, "Tim Donahue" <notifications@github.com> wrote:

Ian, do you want to keep this request open?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mghpcc-projects/user_level_slurm_reservations/pull/9#issuecomment-343183492>,
or mute the thread

**Comment by Izhmash** [comment]
I've added logic to replace or otherwise insert the HOME, PATH, and LOGFILE variables in the prolog, epilog, and monitor .sh files.  The commands check for the existence of any of the variables before editing them.

**Comment by Izhmash** [comment]
@tpd001 is this what you had in mind for editing the path variables?  I tried to keep the naming consistent with what is already in place.  Let me know if there's anything else you require besides what I've implemented here.

**Comment by tpd001** [comment]
OK to merge. 
Modifications to new install Makefile will be required; I will do that.

**Pull request merged**
